EXENAME = main
OBJS = main.o Edge.o Graph.o Node.o

CXX = clang++
CXXFLAGS = -std=c++0x -c -g -O0 -Wall -Wextra
LD = clang++
LDFLAGS = -std=c++0x

all: $(EXENAME)

$(EXENAME): $(OBJS)
	$(LD) $^ $(LDFLAGS) -o $@

Edge.o: Edge.cpp
	$(CXX) $< $(CXXFLAGS)

Graph.o: Graph.cpp
	$(CXX) $< $(CXXFLAGS)

Node.o: Node.cpp
	$(CXX) $< $(CXXFLAGS)

clean:
	-rm -f *.o $(EXENAME)